### ISSUE TITLE
Error when searching for specific criteria

### ISSUE THREAD

**Issue by malonehedges** [justinnhli/subitize#1]
When searching for the criteria as shown in the image, a TypeError is thrown.

Gist of whole error: https://gist.github.com/anonymous/fcc2212c5e6dbc5d57a3ad556f479f86

Occurred after running `python3 subitize-app.py` in cloned repo.

![image](https://cloud.githubusercontent.com/assets/12092296/14838957/a075331a-0bdb-11e6-9869-4b46c6ee67ac.png)

![image](https://cloud.githubusercontent.com/assets/12092296/14838993/e20f0d8c-0bdb-11e6-8e48-5d09d1cffca6.png)

**Comment by malonehedges** [comment]
It appears to happen when using the `Meets on:` advanced search feature regardless of core requirement.

**Comment by justinnhli** [comment]
Should be fixed by ccb11de721e2bf03bd1daeb7ac8f1a0900943508
